# fly.toml app configuration file generated for shoptrack-frontend on 2025-09-18T20:46:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shoptrack-frontend'
primary_region = 'fra'

[build]
  [build.args]
    VITE_API_HOST = 'api.shoptrack.app'
    VITE_API_PORT = '443'
    VITE_API_PROTOCOL = 'https'
    VITE_ENABLE_DEVTOOLS = 'true'
    NODE_ENV = 'production'
    # Add other required variables here as needed:
    # VITE_GOOGLE_CLIENT_ID = 'your-google-client-id'
    # VITE_APPLE_CLIENT_ID = 'your-apple-client-id'
    # VITE_ERROR_LOGGING_ENDPOINT = 'your-endpoint'
    # VITE_ERROR_LOGGING_API_KEY = 'your-api-key'

[env]
  # Runtime environment variables (not used by Vite)
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/usr/share/nginx/html'
  url_prefix = '/'
